---
version: "3.8"
services:
  webserver:
    command: sh -cx "docker-php-ext-install mysqli && echo 'restart...' && apache2-foreground"
    container_name: apache-webserver
    image: php:8.0-apache
    ports:
    - 8000:80
    depends_on:
    - db
    volumes:
    - ./:/var/www/html/
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: testdb
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpass
    ports:
    - 9906:3306
...
