---
version: "3.8"
services:
  php:
    command: sh -cx "apt-get update && apt-get install -y libgd-dev && docker-php-ext-install
      gd && docker-php-ext-install mysqli && php-fpm"
    image: php:7.4-fpm
    volumes:
    - ./:/www
  webserver:
    container_name: nginx-webserver
    image: nginx:1.13-alpine
    ports:
    - 80:80
    volumes:
    - ./:/www
    - ./config/webserver/nginx/config.txt:/etc/nginx/conf.d/default.conf
    links:
    - php
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: testdb
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpass
    ports:
    - 9906:3306
...
