image: 'mysql'

restart: 'always'

environment:
  MYSQL_ROOT_PASSWORD: 'test123'
  MYSQL_DATABASE: 'testdb'
  MYSQL_USER: 'mysqluser'
  MYSQL_PASSWORD: 'mysqlpass'

ports:
  host: 9906
  client: 3306

requires:
  webserver:
    php-ext:
      - mysqli